# Generated by Django 5.2.5 on 2025-08-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=200)),
                ('duracion', models.CharField(choices=[('1 semana', '1 semana'), ('2 semanas', '2 semanas'), ('3 semanas', '3 semanas'), ('4 semanas', '4 semanas'), ('8 horas', '8 horas'), ('16 horas', '16 horas'), ('24 horas', '24 horas')], max_length=20)),
                ('plataforma', models.CharField(choices=[('Udemy', 'Udemy'), ('Coursera', 'Coursera'), ('Platzi', 'Platzi'), ('edX', 'edX'), ('YouTube', 'YouTube')], max_length=50)),
                ('dificultad', models.CharField(choices=[('Facil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=20)),
            ],
        ),
    ]
